### PR TITLE
Create Teams' Contact Magic Links

### PR DESCRIPTION
**Pull request by micahmills**
Creates a User Magic Link app to show all contacts for teams that a user is in.

### CODE REVIEW

**Comment by cairocoder01** [comment]
@micahmills Thanks for working on this. I'm not sure if it's a bad local site that I'm trying to test on, but I'm not seeing this magic link template available from the magic links plugin. Can you share some details of how to test this? Maybe also add something in the readme as minimal documentation too?

**Comment by cairocoder01** [comment]
Looking at the logs, it seems to be throwing an error by the inclusion of the `location` field, basically saying it doesn't exist. I assume there's a difference in our mapping setup. My test site doesn't have any mapbox token. We should probably take that into account and not add that field if there's no geocoding tokens.

**Comment by micahmills** [comment]
I will take a look. I am don't have a mapbox token on my local site or my staging server either so I am not sure where the error is coming from.

**Comment by micahmills** [comment]
Hey @cairocoder01 I when ahead and moved everything into a Magic Links template. Eventually I would like to have a template for teams records to show all the contacts for that team. This would allow a magic link without logging in. This works right now, but we need to update the magic links plugin with your connected fields changes so that you can include all the DT fields from the contact or group records in the team.

**Comment by cairocoder01** [comment]
@micahmills Functionality looks pretty good. I haven't dug into the code, but I assume you just copied a lot so I'll leave it alone.

A few bugs to note:
- When saving a contact and the success banner shows at the top, the link to the exclamation icon seems to be missing
- The title of the table still says "Subassigned". I'm guessing this should be Team Contacts or something

image

- If I open it for a contact that's not on a team or doesn't have any contacts, a PHP error shows up: 
image

Otherwise this looks great! Thanks for doing it. With those 3 small fixes I can push this through.

**Comment by cairocoder01** [comment]
Looks great! Thanks @micahmills !

**Pull request merged**
